src/tree.rs

Pattern matching captures all the different methods available for Frag. Therefore the catchall won't be triggered which results in a build error.

Fix "unreachable pattern" error

---

Cargo.toml
src/lib.rs
src/log/iobuf.rs
src/log/lss.rs
src/log/reservation.rs
tests/test_log.rs

~40% perf improvement by assigning the next log file offset at the time of sealing a buffer
cleanup of remaining code relying on hardcoded constants
some debugging improvements, log support (you won't see these log messages unless you call `env_logger::init();` in your code, but adding these messages makes seeing info easier in the future when debugging)

log speedup

---

Cargo.toml
src/page/mod.rs
src/page/page_cache.rs
src/radix.rs
src/stack.rs

I've added `Send` as a requirement for `Stack` and `Radix` contained types, as they may be transmitted to another thread. I've added `Sync` as a requirment for anything that is iterated over in the `Stack` as multiple threads may view references to it simultaneously. I've added `Sync as a requirement for anything contained in a `Radix` as it may be retrieved by multiple threads simultaneously.

implement Send and Sync on types that are used in shared structures

---

Cargo.toml
src/bin/bench.rs

Adds padding for keys and values so that it's more likely to e.g. `get` a previously inserted tree entry.
This way we don't have to seed the tree with dummy data before running the benchmarking tool.

Add padding for keys and values

---

Cargo.toml
src/bin/stress2.rs
src/config.rs
src/page/page_cache.rs
src/tree/mod.rs
src/tree/node.rs
tests/test_tree.rs

1.5m failed reads/s on an empty tree
750k reads/s 4 threads all doing get's with 8-byte keys and 0 byte values
230k ops/s with a workload that does 1 type of op per thread
crappy laptop, 2 cores with hyperthreading
probably enough tuning for the short term, time to focus more on release engineering now

tune page_in a bit

---

Cargo.toml
src/bin/stress.rs
src/config.rs
src/log/iobuf.rs
src/metrics.rs

O_DIRECT skips the OS pagecache entirely, basically doing DMA. It makes it so the OS does not cache any data in memory about files, as it normally does. This is sometimes useful if the data on disk is different from what the application actually uses (compression, serialization, etc...) and there's a userspace cache already (like what we have). A downside is you can get WORSE performance if you mix O_DIRECT and non-O_DIRECT work, and you have to align all operations to the device's specified alignment (usually 512, but sometimes not!)
This work basically gives us a quick switch to flip when we want to give it a spin!
Note that it's not correct yet, since the 512 hardcoded alignment could be different sometimes, so we need to check that dynamically in the future.

add feature flag for using O_DIRECT on writes. closes #111.

---

Cargo.toml
lib/neon-sled/native/src/lib.rs
src/ds/art.rs
src/ds/radix.rs
src/ds/stack.rs
src/io/log/segment_accountant.rs
src/io/page/page_cache.rs
src/lib.rs
src/tree/iter.rs
src/tree/tree.rs
tests/test_pagecache.rs

`crossbeam-epoch` is finally released.  How about moving from `coco` to `crossbeam-epoch`?
In my machine, the performance of this PR is comparable to the master.  Here is a one-shot measurement of `cargo build --bin=stress --features=stress,zstd; hack/flamerun.sh ./target/debug/stress --duration 5; firefox ./flamegraph.svg`:
crossbeam-epoch
```
did 26916 ops
did 28559 ops
did 28504 ops
did 29216 ops
did 27831 ops
did 141026 total ops in 5 seconds. 28205 ops/s
```
master
```
did 26796 ops
did 28563 ops
did 26291 ops
did 29387 ops
did 28827 ops
did 139864 total ops in 5 seconds. 27972 ops/s
```
@stjepang, thank you for helping me in debugging!
Closes #116

Porting to crossbeam-epoch

---

src/io/mod.rs
src/io/page_cache.rs
src/io/segment.rs
src/io/snapshot.rs
tests/test_pagecache.rs

remove segment state from the `Snapshot` itself, recompute it on recovery from the page table. reduce bug space and concentrate responsibility.

simplify snapshot state

---

src/config.rs
src/io/iobuf.rs
src/io/page_cache.rs
src/io/segment.rs
src/io/snapshot.rs
src/lib.rs
tests/test_log.rs
tests/test_pagecache.rs

there is now a configurable minimum number of elements that can be put into a single segment. when we have fewer than `page_consolidation_threshold` * `min_items_per_segment` pages in a segment, it can be marked as "draining" for accelerated relocation of the remaining pages, so that the segment may be reused.

fractional segments

---

src/io/mod.rs
src/io/page_cache.rs
src/io/segment.rs
src/io/snapshot.rs
src/tree/mod.rs
tests/test_pagecache.rs
tests/test_tree.rs

This adds more information about the state of various pages, so that it can be reasoned about more effectively in tests and by users. This makes the testing model much less ambiguous, so hopefully future bugs will be more clear when they pop up in quickcheck.

track page allocations

---

README.md
crates/pagecache/README.md

The READMEs for sled and pagecache were rendering incorrectly on crates.io, due to some embedded merit badges with non-HTTPS links, and an image that wasn't actually linked to the raw image. Fix the links appropriately.

Use HTTPS for merit badges, and GitHub raw link for embedded images

---

crates/pagecache/src/config.rs
crates/pagecache/src/io/iobuf.rs
crates/pagecache/src/lib.rs
crates/pagecache/src/metrics.rs

Hi!  I just replaced a few mention of "sled" into that of "pagecache" in the pagecache crate.  Because maybe pagecache can be a standalone crate that can be used outside of the context of sled :)  Thanks!

pagecache: Replace reference to sled to that of pagecache

---

crates/pagecache/src/io/iobuf.rs
crates/pagecache/src/io/log.rs
crates/pagecache/src/io/page_cache.rs
crates/pagecache/src/io/reader.rs
crates/pagecache/src/lib.rs

The pagecache crate measure the time spent on running a piece of code for several times.  This PR introduces an RAII-style and lambda-style utility for measuring the time, which, IMHO, slightly improves the readability of the code.

pagecache: Add RAII-style and lambda-style measure

---

crates/pagecache/src/io/page_cache.rs
crates/pagecache/src/io/segment.rs

In this PR, `PidDropper` and `SegmentDropper` is inlined in the calls to `epoch::Guard::defer()`.  I think it's slightly more readable: you literally defers to call a function, rather than defers to drop an object.

pagecache: Inline droppers

---

crates/tests/tests/test_crash_recovery.rs
crates/tests/tests/test_pagecache.rs
crates/tests/tests/test_tree.rs

Fix some warnings when running `cargo test`.
Also there are a lot of operations like set, del called without check the result.

fix some test warnings

---

crates/pagecache/src/io/iterator.rs

choosing NOT to use FADV_DONTNEED for completed segments because they may be likely to be populated again once the system is running, based on temporal locality assumptions. none of this will matter anyway once we flip to O_DIRECT.

use FADV_WILLNEED on a segment before iterating over it. Closes #282.

---

.travis.yml
README.md
crates/pagecache/Cargo.toml
crates/pagecache/src/io/iobuf.rs
crates/pagecache/src/io/segment.rs
crates/pagecache/src/lib.rs
crates/sled/Cargo.toml

Discussion points:
Let me know if you want me to change stuff! :-)
Issue #145 for reference.

Compilation for 32-bit architectures on nightly

---

crates/pagecache/src/io/segment.rs

Apparently I missed a case, where `--features=nightly` and target is a 64 bit arch...
I'm wondering whether it would be better to use `#[cfg(nightly)]` everywhere, and only use `#[cfg(target_pointer_width="32")]` for the error message. That way, the i64 type gets thoroughly tested with the nightly flag, independently from whether we're targetting 32 bit...
(fixes #304)

 64-bit target with `nightly` feature doesn't compile anymore.

---

crates/model/src/lib.rs

A few small fixes that make the doctests compile (tested using Rust 1.27.0).

Fix model doctests compilation

---

crates/model/src/lib.rs

Currently, using the latest version of proptest along with the model crate will result in breaking code with a fairly opaque error:
```
error[E0614]: type `test_model::Op` cannot be dereferenced
--> tests/model.rs:10:5
|
10 | /     model! {
11 | |         Model => let m = AtomicUsize::new(0),
12 | |         Implementation => let mut i: usize = 0,
13 | |         Add(usize)(v in 0usize..4) => {
...  |
37 | |         }
38 | |     }
| |_____^
|
= note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
This is with proptest 0.8. Apparently, some types are now passed by value instead of by reference, causing the model! macro to fail. Downgrading to 0.7 fixes this; it took me a bit to get to the bottom of …

Added helpful notice regarding proptest versions.

---

.travis.yml
Cargo.toml
README.md
benchmarks/stress2/Cargo.toml
crates/model/src/lib.rs
crates/pagecache/Cargo.toml
crates/pagecache/src/config.rs
crates/pagecache/src/diskptr.rs
crates/pagecache/src/ds/stack.rs
crates/pagecache/src/io/blob_io.rs
crates/pagecache/src/io/iobuf.rs
crates/pagecache/src/io/iterator.rs
crates/pagecache/src/io/log.rs
crates/pagecache/src/io/mod.rs
crates/pagecache/src/io/page_cache.rs
crates/pagecache/src/io/reader.rs
crates/pagecache/src/io/reservation.rs
crates/pagecache/src/io/segment.rs
crates/pagecache/src/io/snapshot.rs
crates/pagecache/src/lib.rs
crates/pagecache/src/metrics.rs
crates/pagecache/src/result.rs
crates/pagetable/Cargo.toml
crates/sled/Cargo.toml
crates/sled/src/tree/tree.rs
tests/tests/test_crash_recovery.rs
tests/tests/test_log.rs
tests/tests/test_pagecache.rs
tests/tests/test_tree_failpoints.rs

this addresses one of the larger pain points that limited use cases of sled. now you can store large values, which are placed in the `blobs` subdirectory, indexed by original lsn. at attempt is made to keep them linearized with the log, by reading all post-checkpoint blobs and verifying their crc before advancing the associated log index during recovery. any blobs that have a higher lsn than the recovered log are deleted, as they are from an unrecoverable future. if there is interest maybe they can be moved to a "lost and found" directory instead, though.
these changes will be available in sled `0.15.18` and pagecache `0.4.6`.

support for off-log external blobs. closes #198.

---

benchmarks/stress2/src/main.rs

kv-len was present in the long help message but not the short one, so was ignored by DocOpt

Fix `USAGE` string in stress2

---

crates/sled/src/lib.rs
crates/sled/src/prefix.rs
crates/sled/src/tree.rs

Closes #285
Output from `stress2`:
```
master
traverse |        2.5 |       73.9 |      129.3 |      224.1 |     8537.7 |     699934 |     27.632
prefix-opt
traverse |        1.7 |       80.8 |      135.9 |      206.9 |     1045.5 |     649053 |     27.825
```
There's not much change in the smaller columns, but since that's only a handful of us, I assume it's not significant. The max is improved by more than 8x. I don't know how to interpret the 'sum' column.
Flamegraphs:
master:
prefix-opt:
These flame graphs show the same view of stress2. On master, there is significant time spent in `prefix_decode` and jemalloc. On the prefix-opt branch, both have disappeared (they are not even present on hovering the small items on the far right, and nor is any other tree comparison function.
r? …

Optimise prefix comparison

---

crates/pagecache/src/ds/stack.rs
crates/pagecache/src/pagecache.rs
crates/pagetable/src/lib.rs
crates/pagetable/tests/model.rs
crates/sled/src/tree.rs
tests/tests/test_pagecache.rs

concurrency tests uncovered a panic where we were assuming that we cound allocate -> replace -> free and have the free work using the pointer returned from replace. But the page may change locations if the segment accountant wishes to clean up its segment. Now we no longer assume it is unchanged.

fix page relocation race condition

---

README.md
benchmarks/stress2/src/main.rs
crates/pagecache/src/config.rs
crates/pagecache/src/constants.rs
crates/pagecache/src/iobuf.rs
crates/pagecache/src/lib.rs
crates/pagecache/src/segment.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs
tests/tests/test_log.rs
tests/tests/test_tree_failpoints.rs

adds a default tree open method
allows databases to be moved around now
fewer configuration options
add sloped cleanup thresholds that should drive 10% more cleanup efforts towards lower segments to keep db's leaner

simplify config. Closes #326.

---

benchmarks/stress2/src/main.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs
tests/src/tree.rs
tests/tests/test_crash_recovery.rs
tests/tests/test_tree.rs
tests/tests/test_tree_failpoints.rs

This pull request change the `Tree` methods to accept a `&[u8]` instead of a `Vec<u8>` where this is possible, it will remove the restriction of forcing the user to allocate on the heap. This changes happen almost always when a key is asked.
This is a breaking change, we must bump the minor version.
There is another way to make this improvement: Making the methods asking for a key that implement `AsRef<[u8]>`. This way it will not be a breaking change. But I think we didn't make sled reach 1.0 for the moment so we can break things :)

Update methods to accept an AsRef<[u8]> type instead of a Vec<u8> 

---

tests/tests/test_tree.rs

This fixes the `test_tree::tree_subdir` test

Fixing the tree_subdir test

---

crates/sled/src/bound.rs
crates/sled/src/data.rs
crates/sled/src/iter.rs
crates/sled/src/materializer.rs
crates/sled/src/node.rs
crates/sled/src/tree.rs

This introduces u64 and saturating adds for size-related math internal
to sled.

sled: use saturating u64 for size calculations

---

benchmarks/stress2/Cargo.toml
crates/pagecache/Cargo.toml
crates/pagecache/src/lib.rs
crates/pagecache/src/measure_allocs.rs
crates/pagecache/src/metrics.rs
crates/sled/Cargo.toml

@utaal Just added a pretty simple allocation counter based on @rw's counter in the flatbuffers codebase, but using AtomicUsize so it works across threads.
recommended to run from benchmarks/stress2:
```
cargo run --features=measure_allocs --  --threads=1
```
non-release mode on my laptop does 250k high-level operations in 10 seconds, generating nearly 4 million allocations with about 840mb of total allocation.
release mode: roughly 10x higher in all measurements over 10 seconds.
TONS of low-hanging fruit :] Now this can be a fun game to get the number down

Optionally measure allocations

---

crates/sled/src/iter.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs

docs should be easier to quickly understand, so we should get rid of unnecessary type pollution

reduce exported types

---

.gitignore
tests/tests/test_log.rs

Share a log among several threads, and also share an AtomicUint counter.
Threads will attempt to successfully CAS on the counter to increment it by 1. 
If this succeeds, that signals to the test complete its log reservation,
otherwise it will abort.
This counter indicates the number of sucessful writes to the shared log.
The contents of the write will be the value read from the counter.
Finally, iterate through the log, and assert that the number of
successful entries exactly matches the success counter, and that the
values increment sequentially.
Refs #404

Add concurrent log test

---

.travis.yml
tests/tests/test_crash_recovery.rs

This is because we sometimes have the child in fork return
exit code 4, causing the process to exit before logging any
information.

Skip fork-based crash tests on macos.

---

crates/pagecache/README.md
crates/pagecache/src/ds/stack.rs
crates/pagecache/src/pagecache.rs
crates/pagecache/src/tx.rs
crates/pagetable/src/lib.rs
crates/sled/src/context.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs

Here are some orthogonal improvements:
- Rust code highlight in pagecache's README
- Use `guard.defer_destroy()` instead of `guard.defer()`.  See [the API doc](https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-epoch/src/guard.rs#L199).
- Create `Tx::new()`.
- Fix a documentation bug.
- Use `Relaxed` instead of `SeqCst` in pagetable's `drop`.  It is sound because the destructor is accessing the data without contention.

Several orthogonal improvements

---

crates/sled/src/ivec.rs

It is now possible to specify formatting rules, the "underlying" slice will be informed of the outer formatting rules. For example the `{:x?}` will now correctly display the slice in its hex representation.

Make the IVec Debug impl support formatting

---

crates/pagecache/src/config.rs
crates/pagecache/src/iobuf.rs
crates/pagecache/src/iterator.rs
crates/pagecache/src/meta.rs
crates/pagecache/src/parallel_io.rs
crates/pagecache/src/reservation.rs
crates/pagecache/src/tx.rs
crates/sled/src/iter.rs
crates/sled/src/node.rs
crates/sled/src/prefix.rs

I ran rustfmt and clippy.  Fixed all clippy errors, but left a few warnings on "cyclomatic complexity", e.g.:
```
warning: the function has a cyclomatic complexity of 29
--> crates/sled/src/iter.rs:210:5          
|                                      
210 | /     fn next_back(&mut self) -> Option<Self::Item> {
211 | |         let _measure = Measure::new(&M.tree_scan);
212 | |                        
213 | |         if self.done {                                   
...   |                                                                                             
445 | |         }                                                                                   
446 | |     }                                                                                       
| |_____^ …
```

Rustfmt and clippy

---

crates/sled/src/ivec.rs

Implementing this trait make the `IVec` more easy to use with comman type (i.e. [`io::Cursor`](https://doc.rust-lang.org/std/io/struct.Cursor.html)).
Do you think the `IVec` can be considered a smart pointer? https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-deref

Implement AsRef for IVec

---

crates/sled/src/subscription.rs
crates/sled/src/tree.rs

This pull request reduce the number of times a value is cloned in the `set`, `merge` and `cas` Db methods. It can be costly especially for big values.
To fix that I directly put the user value inside of an `IVec` this way cloning is not costly. By the way I changed the `Event::Set/Merge` types to be more consistent with the current Db API, returning the values as `IVec` and not `Vec<u8>`.

Reduce the number of times a value is cloned

---

crates/pagecache/src/config.rs

This pull request change two things, it enables the pagecache compression feature checks if the compression feature has been set when `use_compression` is set to `true`.
I faced the problem of running sled without the `compression` feature active but with the `use_compression` config builder param set to `true` (the default value) and sled didn't tell me anything.
Even worst: I created a database with the `compression` feature and tried to read it, get values from trees, with another program without the `compression` feature active, sled did not say anything but did not returned any entry, like they were empty.
So there is two solutions to fix this problem:
- keeping the `use_compression` param set to `true` by default **but** make the `compression` feature enabled by default or
- set the …

Check if the compression feature is enabled

---

crates/sled/src/data.rs
crates/sled/src/lib.rs
crates/sled/src/prefix.rs

I tested and assumed that the `ptrs` are already sorted and that prefix encoded keys are sorted the same that non encoded ones (is that named "ordering transitivity" ?).
I will rebase on master once #592 is merged, if it is 😄 
So in this rewrite I no longer need to construct a decoded sorted Vec but only need to decode the middle key (`split`) and create a new Vec of half the size of `ptrs` re-encoded using the previously extracted middle key (`split`).
I also rewrite the `prefix_decode` and `prefix_encode` functions removing the unsafe code that doesn't seems to be needed and introduced a new `prefix_reencode` function that `decode` and `encode` using the the old and new prefix.
This update reduced the usage percentage of the `Data::split` method from 46.2% to 25.47% and make my program …

Rewrite the Data split method

---

crates/sled/Cargo.toml
crates/sled/src/ivec.rs

I rewrote the De/Serialize impls of the `IVec` type, in the old one the `serialize_bytes` method was only called for the `Remote` variant and not the `Inline` one (which would call `serialize_seq` with `u8`).
This PR makes my code takes from 16mins (with the #593 patch) to 13mins 30secs by reducing the `Node::serialize` usage from 17.29% to 3.71%.
I now that serde will be removed as soon as flatbuffer land.
Let me rebase on master when #593 is merged 😄 
[flamegraphs-before-after-ivec-de-serialize.zip](https://github.com/spacejam/sled/files/2999802/before-after-ivec-de-serialize.zip)

Improve the IVec bytes de/serializing

---

crates/pagecache/src/logger.rs
crates/sled/src/tree.rs

@Kerollmops for workloads I tried with larger values (800 bytes+), this caused a really major speedup. Basically, we were doing a ton of wasted work trying to split nodes even when we detected that we were failing some of the recursive tree splits. Now we bail as soon as we fail once, because it's incredibly likely that we will not win any others either.

some write optimizations

---

crates/pagecache/Cargo.toml
crates/pagecache/src/metrics.rs
crates/sled/Cargo.toml
crates/sled/src/tree.rs
tests/tests/test_tree_failpoints.rs

@Kerollmops this basically makes recursive_split drop off the flamegraph completely during the first few seconds of operation, and it should shave a few seconds off your workload again, but I'd be curious how much!

Skip parent splits in recursive split, since they are handled cooperatively in path_for_key

---

crates/sled/Cargo.toml
crates/sled/src/tree.rs

I do not know if it would make any sense to add this helping function to the Tree type. Should it be named like this, isn't there a specific name for this kind of function?
It could be a dangerous function because it could block the thread for an infinite time. In another hand I read somewhere that "lock-free" things are guaranteed to make progress (not like Mutex), I do not know if it can be applied to this "high level" data structure.

Introduce update_and_fetch/fetch_and_update methods

---

crates/pagecache/src/constants.rs
crates/pagecache/src/iobuf.rs
crates/pagecache/src/logger.rs
crates/pagecache/src/segment.rs
crates/pagecache/src/snapshot.rs

This splits the physical implications away from the recovery logic changes in #606

Add max stable lsn to segment trailers

---

crates/sled/src/ivec.rs

Hiding the inner enum making it impossible to read the raw inline array value therefore avoiding user mistakes (reading out of bound bytes form the `IVec::Inline` variant).

Make the IVec type safer for library users

---

crates/sled/src/ivec.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs

This updates the API examples for `Tree`, as discussed in issue #533. The basic pattern I'm following is
```
assert_eq!(t.del(&[1]), Ok(Some(sled::IVec::from(vec![1]))));
```
That is, I'm writing out the full return type on the right hand side, including `IVec::from` for the conversion. This isn't the most concise way to write it, but I think it's nice to be as explicit as possible in the API docs. The exception is for iterator methods, where I do
```
assert_eq!(r.next().unwrap(), Ok((vec![2], IVec::from(vec![20]))));
```
That's because I'm assuming people are already familiar with the iterator API, so they already know that next returns an option.

Update API examples.

---

crates/pagecache/src/config.rs
crates/sled/src/data.rs
crates/sled/src/frag.rs
crates/sled/src/meta.rs
crates/sled/src/node.rs
crates/sled/src/tree.rs

This implements a function to merge nodes.
1. Install `MergeIntetion` in a parent, pointing at a child
2. Install a `MergeCap` at the child, preventing writes to it
3. Merge child node into left sibling
4. Complete merge and swap parent pointers

Merging nodes

---

crates/sled/src/tree.rs

Adds the explanation from @spacejam from #661 to the `get_gt` function. I don not know if this is useful for you, if it is not feel free to close this PR. If you would like I will expand this PR to also extend the documentation for `get_lt` and `range` in a similar way.

add order explanation and example to `Tree::get_gt` for multi byte keys

---

crates/sled/src/tree.rs

Relaxing the `update_and_fetch` and `fetch_and_update` `Tree` methods by accepting `FnMut` functions as these functions are not called concurrently.

Relax the some Tree methods to accept FnMut functions

---

.travis.yml
crates/pagecache/src/event_log.rs
crates/pagecache/src/iobuf.rs
crates/pagecache/src/pagecache.rs
crates/pagecache/src/segment.rs
crates/sled/src/context.rs
crates/sled/src/db.rs
tests/Cargo.toml

Remove segment-related event log items, as it's not deterministic enough to be useful. Move page-related event logging to the pagecache itself. Update travis config.

fix up event log and turn it back on during tests

---

crates/pagecache/src/lib.rs
crates/sled/src/batch.rs
crates/sled/src/context.rs
crates/sled/src/db.rs
crates/sled/src/iter.rs
crates/sled/src/lib.rs
crates/sled/src/meta.rs
crates/sled/src/tree.rs

This is incomplete for a few reasons:
* causes system to completely stall if all io buffers are filled while the log pin is held
* doesn't support multi-tree batches yet
* doesn't support merge operations yet
None of these things require major engineering effort to fix, but I want to move this into master to keep things rolling quickly.

Rudimentary Batch update support

---

crates/pagecache/Cargo.toml
crates/pagecache/src/debug_delay.rs
crates/pagecache/src/ds/lru.rs
crates/pagecache/src/iobuf.rs
crates/pagecache/src/lib.rs
crates/pagecache/src/logger.rs
crates/pagecache/src/metrics.rs
crates/pagecache/src/reservation.rs
crates/sled/src/flusher.rs
crates/sled/src/view.rs
tests/tests/test_log.rs
tsan_suppressions.txt

This allows dynamic numbers of io buffers to remain incomplete over long stretches of time, effectively fixing writebatches.

flexible iobufs. Closes #678. Closes #689.

---

crates/pagecache/src/lib.rs
crates/pagecache/src/pagecache.rs

reduces logged messages to bare serialized bytes for the relevant type, as signaled in the MessageHeader.kind field.

no logged update

---

crates/pagecache/Cargo.toml

Code generation by the underlying library is now disabled by default and
can be opted-in (and re-exported) via the `fail/failpoints` feature.
Ref: https://github.com/pingcap/fail-rs/blob/v0.3.0/CHANGELOG.md

cargo/pagecache: update to fail 0.3

---

README.md
crates/sled/src/db.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs

I don't know how everybody is gonna like this. This replaces `db::start_default` with `db::open` to be easier and something that everyone expects from the API, similar to a `std::fs::File`. 
Now, I don't like that there is `db::start(config)` left and it's inconsistent with the `db::open(path)`. I would replace it with something like `db::init(config)` or `db::open_config(config)`. What do you think?
It seems like there is still no func overloading in Rust.

replace db::start_default with db::open

---

crates/pagecache/src/ds/stack.rs
crates/pagecache/src/logger.rs
crates/pagecache/src/pagecache.rs
crates/pagecache/src/tx.rs
crates/sled/src/context.rs
tests/src/tree.rs
tests/tests/test_log.rs
tests/tests/test_pagecache.rs
tests/tests/test_tree_failpoints.rs

latest rustc is unhappy about missing dyn`s before boxed traits, and
there are some places where the compiler can auto infer lifetime context.

add dyn for boxed traits

---

crates/pagecache/src/config.rs
crates/pagecache/src/ds/pagetable.rs
crates/pagecache/src/ds/stack.rs
crates/pagecache/src/lazy.rs
crates/pagecache/src/lib.rs
crates/pagecache/src/logger.rs
crates/pagecache/src/pagecache.rs
crates/pagecache/src/promise.rs
crates/pagecache/src/segment.rs
crates/sled/src/batch.rs
crates/sled/src/context.rs
crates/sled/src/data.rs
crates/sled/src/db.rs
crates/sled/src/flusher.rs
crates/sled/src/ivec.rs
crates/sled/src/materializer.rs
crates/sled/src/node.rs
crates/sled/src/prefix.rs
crates/sled/src/subscription.rs
crates/sled/src/tree.rs
examples/crdt_merge_store/src/lib.rs
examples/playground/src/main.rs
tests/src/lib.rs
tests/src/tree.rs

Here's a raft of fixes for #760. I mostly skipped lints about sign loss/truncation on casting, function arguments that could be passed by reference instead, and binding names.

Some fixes for Clippy pedantic lints

---

crates/pagecache/src/pagecache.rs
crates/sled/src/batch.rs
crates/sled/src/db.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs
crates/sled/src/tx.rs
tests/tests/test_tree.rs

this is an implementation of a simplified transaction API that can be used for single Trees or tuples of Trees for multi-Tree transactions.
in-scope:
* nice API
* serializable
future work:
* scans
* optimistic concurrency control
* MVCC
todo:

simple multi-Tree serializable transactions

---

crates/pagecache/src/config.rs

Implementation of https://github.com/spacejam/sled/issues/685: limit cache size to the cgroup memory limit on linux. It does not contain tests tho.

limit cache size to the cgroup memory limit on linux

---

tests/tests/test_tree.rs

This adds one more assert to the `concurrent_tree_transactions` test, after all the reader and writer threads have joined. It checks that the entries have returned to their original values (since they get swapped an even number of times). If any of the swapping transactions gets lost, and their durability isn't maintained, this assert will catch the issue.

Add check to transaction test after writers finish

---

crates/pagecache/src/config.rs
crates/pagecache/src/debug/delay.rs
crates/pagecache/src/debug/mod.rs
crates/pagecache/src/ds/dll.rs
crates/pagecache/src/ds/lru.rs
crates/pagecache/src/ds/mod.rs
crates/pagecache/src/ds/pagetable.rs
crates/pagecache/src/ds/stack.rs
crates/pagecache/src/ds/vecset.rs
crates/pagecache/src/lazy.rs
crates/pagecache/src/lib.rs
crates/pagecache/src/logger.rs
crates/pagecache/src/pagecache.rs
crates/sled/src/data.rs
crates/sled/src/iter.rs
crates/sled/src/lib.rs
crates/sled/src/tree.rs
crates/sled/src/tx.rs
tests/check_cross_build.sh
tests/src/tree.rs

https://github.com/spacejam/sled/issues/760
- fixed some clippy for `ds` mod
- fixed cycle dependency for `ds` mod
- make some ds mod structs names easier
- simplify some code
- removed Node{1,2} drop code dup
- remove PageId abstraction leak to the DLL, LRU
- used inlined `safe_usize` helper instead of `usize::try_from.unwrap`
- add a script that helps to check cross-compilation locally
- split_fanout made more natural to the target types and moved closer to the traversal

fix some ds mod warns and refactor it a little #795

---

tests/tests/test_tree_failpoints.rs

This PR adds a separate Flush operation to the `test_tree_failpoints.rs` quickcheck tests. The idea for this was in one of the comments in the file. The reference data structure no longer holds a `(u16, bool)` indicating the last value, and whether it's certain or not, rather, it now it holds a `Vec<Option<u16>>` of possible values. The Set and Del operations add to the list of possible values, while the new Flush operation discards all but the last possible value.
I didn't discover any new bugs with this change. I'd welcome input on the probability distribution in `Op::arbitrary`. BTW, feel free to squash this PR, it was a real garden path, and I committed frequently along the way.

Flush operation in failpoint tests

---

tests/tests/test_tree_failpoints.rs

This is a followup to #807
* After iterating through the tree, check the rest of the reference, in case the tree is missing the last keys.
* Keep track of crashes, and keep the reference uncertain about operations that happened after a flush and before a crash.

Further improvements to failpoint test

---

CHANGELOG.md
src/config.rs
src/event_log.rs
src/lib.rs
src/pagecache/diskptr.rs
src/pagecache/iobuf.rs
src/pagecache/iterator.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/pagecache/pagecache.rs
src/pagecache/parallel_io.rs
src/pagecache/reader.rs
src/pagecache/reservation.rs
src/pagecache/segment.rs
src/pagecache/snapshot.rs
tests/test_crash_recovery.rs
tests/test_log.rs
tests/test_pagecache.rs
tests/test_tree.rs
tests/test_tree_failpoints.rs
tests/tree/mod.rs

- LogOffset makes code much much more readable and easier to understand
- because it now always divides the LSN or OFFSET by the SegmentSize

further code improvements related to basic db primitives naming

---

src/tree.rs

The documentation currently says that if the ``Tree::cas()`` operation succeeds, the value returned is a ``Result<(), Option<IVec>>`` -- without really explaining why, or what the inner error value actually is.
This PR adds a doc test to provide the clarity I was missing.

Tree::cas documentation clarification

---

src/tx.rs

This is parallel to #858, but uses a macro to implement Transactional on tuples of two to ten trees. The design of the macro was largely driven by the syntax for indexing into tuples, which requires literals. As such, the main macro takes sequential numbers as arguments. The `repeat_type!` macro uses recursion to turn the list of numbers into a list of a type, repeated that many times. This is used to define the tuple for which the trait is implemented, as well as the `View` associated type.

Macro, impl Transactional on more tuples of trees

---

Cargo.toml
benchmarks/stress2/Cargo.toml
src/pagecache/io_uring.rs
src/pagecache/iobuf.rs
src/pagecache/logger.rs
src/pagecache/mod.rs

At least save 1 syscall on the segment write path. Don't wait for fsync.
Implementation:
- separate write uring queue for writes
- writes usually require 2 SQE per write (write+fsync)
- fsyncs are issued with DRAIN and not waited
- URing uses preallocated iovecs structs and keep Arcs for used bufs
- when submit queue exhausts write() will wait for minimum empty slots
- uring is used via my custom binding to liburing similar to https://github.com/sitano/liburing
URing.pwrite_all(buf, data, offset, fsync) implementation is as follows:
- take lock
- drain completion queue to retain free slots
- reserve required number of SQEs
- if not enought SQE stlots, wait (1 syscall), then drain
- build write
- build fsync if needed
- submit
ISSUE: https://github.com/spacejam/sled/issues/571
TODO:
- …

io_uring: async segment write path

---

src/node.rs
src/pagecache/io_uring.rs
src/pagecache/mod.rs
src/pagecache/reservation.rs
src/pagecache/snapshot.rs
src/serialization.rs

This moves toward applying optimizations where we can serialize our data directly into a concurrent IO buffer without allocating first.

Add better support for zero-allocation serialization

---

src/tree.rs
tests/test_tree_failpoints.rs

this is an issue in the failpoints test runner, rather than a bug in error handling code. it was improperly marking state as certain even though an error was encountered while dropping the database.

debug failpoints

---

tests/common/mod.rs
tests/test_crash_recovery.rs
tests/test_quiescent.rs

Fixes #911. This adds a new test executable that forks, opens a database, waits ten seconds, and drops it. The child process checks its own CPU usage using `libc`, and exits with an error code if it used more than one second. I tested it by making the flusher spawn an infinite loop in a new thread, and here's what the error messages look like.
```
running 1 test
thread '<unnamed>' panicked at 'Database used too much CPU during a quiescent workload. User: 10.262479s, system: 0.015997s (wall clock: 10.262207544s)', tests/test_quiescent.rs:36:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
test test_quiescent_cpu_time ... FAILED
failures:
---- test_quiescent_cpu_time stdout ----
thread 'test_quiescent_cpu_time' panicked at 'child exited abnormally', …
```

Add test for CPU usage with no DB operations

---

src/result.rs

fix warning: `description` is deprecated since 1.41.0: use the Display impl or to_string() 

---

README.md

The import/export names aren't super discoverable in and of themselves given the description in the readme.

Link to import/export docs where README.md mentions manual migrations

---

src/pagecache/io_uring.rs

Calls to io_uring_submit_and_wait may return without
requested number of completed CQEs. It is needed
to check after each call the number of completed
events and do retries.

pagecache/io_uring/drain_cqe: submit can return nothing

---

src/config.rs
src/flusher.rs
src/oneshot.rs
src/pagecache/io_uring.rs
src/pagecache/iobuf.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/pagecache/segment.rs
src/threadpool.rs

This reduces contention by dropping the associated mutex before notifying its condvar. It is safe because anything that is waiting is waiting on specific state to materialize, which is guaranteed to happen before the condvar is pinged.

release linearizing mutexes before notifying condvars

---

benchmarks/stress2/src/main.rs
src/pagecache/iobuf.rs
src/pagecache/iterator.rs
src/pagecache/logger.rs
src/pagecache/mod.rs

This causes recovery time to be cut in half in some cases. It performs a read on an entire segment at a time and iterates in-memory, rather than reading every message one at a time. Also performs half of the read operations for anything that fits in the 128 byte buffer. This may be better set to like 512 or 4096 bytes.

read optimizations. closes #268. closes #944.

---

Cargo.toml
src/pagecache/constants.rs
src/pagecache/logger.rs

luckily 0.31.0 was not yet published to crates.io, so we can just adjust the git tag for the release to this

Fix MAX_MSG_HEADER_LEN to be 32, accounting for max varint len

---

src/config.rs

That helps users who see the message to differentiate between a
generic compression feature, and that there is a feature called
compression.
It would have helped me anyway :).
Edit: And I figured out which compression levels may be used, so I documented that too.

Make using the 'compression' feature easier

---

src/pagecache/iobuf.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/pagecache/segment.rs

a key aspect of reducing contention through the whole system is to reduce reliance on the SegmentAccountant mutex. writers need to check to see if they can help perform GC from time to time, and this lets them use a very low contention mutex connected to a mpsc::Receiver instead of the SegmentAccountant itself.

significant contention reduction for file GC

---

scripts/cross_compile.sh
src/binary_search.rs
src/fastcmp.rs
src/lib.rs
src/metrics.rs
src/node.rs
src/pagecache/pagetable.rs

I would have hoped that this didn't do anything, but it seems to shave off a few % of CPU usage on read-heavy workloads. Maybe we'll stick SIMD-related key comparisons here later on.

use memcmp for key comparisons

---

benchmarks/stress2/src/main.rs
src/config.rs
src/metrics.rs
src/pagecache/mod.rs
src/pagecache/segment.rs
tests/test_crash_recovery.rs
tests/test_space_leaks.rs
tests/test_tree.rs
tests/test_tree_failpoints.rs
tests/tree/mod.rs

this is an area of the codebase that can lead to runaway file growth, and generally has felt like something that is undertested. for now, it makes sense to remove this bit of risky complexity, possibly coming back to it in the future.

remove runtime snapshotting

---

src/concurrency_control.rs
src/db.rs
src/iter.rs
src/lib.rs
src/meta.rs
src/transaction.rs
src/tree.rs

This uses some self-tuning concurrency control logic to avoid taking out reader locks on common tree operations unless the system has ever used something that requires them. This trades a small amount of effort on the transactional workload side for the first operation performed, where it sets the enabled boolean to true and then waits for all in-flight operations to finish via sending a deferred mpsc send over crossbeam-epoch to be executed after all currently active threads are done.
The result of this is that non-transactional/locking operations (checksum is locking, in addition to transactions) and workloads never need to pay the reader lock acquisition costs on every update, which actually speeds things up quite a lot.
For reads on a database with 10k items with 4 byte keys, this …

dynamically enable concurrency control when it actually is needed

---

src/context.rs
src/pagecache/iobuf.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/pagecache/reservation.rs
src/transaction.rs
src/tree.rs
tests/test_log.rs

This cuts out an expensive reader lock acquisition on every log reservation

Use crossbeam-epoch instead of RwLock to reduce contention on the log reservation path

---

src/pagecache/iobuf.rs

This PR fixes #957 by falling back to `File::sync_all` when `libc::sync_file_range` is not supported.

add fallback when `libc::sync_file_range` is not supported

---

src/pagecache/iobuf.rs
src/pagecache/logger.rs

This causes io buffers to be reused until they fill up to the end, reducing allocations and initialization work. This is a lead-up to a significant reduction in reservation contention by leaning more into `Arc`s and lock-free atomic add for reservations.

reuse io buffers for rolled segments

---

src/node.rs
tests/test_tree.rs

This was a hack while implementing reverse iterators that made the tree less than fully general purpose in combination with reverse iterators.

address max key

---

src/transaction.rs
tests/test_tree.rs

This change facilitates that you can setup a batch and then execute it
inside of a transaction. For example:
```rust
let db = config.open().unwrap();
let t1 = db.open_tree(b"1")?;
let mut b1 = Batch::default();
b1.insert(b"k1", b"v1");
b1.insert(b"k2", b"v2");
t1.transaction(|tree| {
tree.apply_batch(&b1)?;
Ok(())
})?;
```
----
This PR is the implementation of #1013 if it is accepted.
----
I did have a spurious fail in the test `log_writebatch`, but I am unsure if 
it is connected to this change in any way.

Change transaction `apply_batch` to take argument by-reference.

---

src/pagecache/iobuf.rs
src/pagecache/logger.rs

This writes bytes past the end of the last message in a segment (`Cap` or otherwise) to fully initialize the buffer. Initializing these bytes avoids UB from passing a partially initialized `&[u8]` to `pwrite_all()`.
Fixes #1032.

Fully initialize the end of IO buffers

---

CHANGELOG.md
README.md
scripts/cross_compile.sh
src/lib.rs
src/pagecache/reservation.rs
src/pagecache/segment.rs
src/stackvec.rs
src/subscription.rs

This makes our MSRV policy clear, tested, and hopefully will increase general feelings around project stability.

Support Rust versions 1.37 and up

---

src/stackvec.rs

Fixes uninitialized memory use by only printing the first `len` entries of the backing array (by using `deref()`). Fix for #1045. [Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=809f6670dae846ce33a659873d2fb399), for kicking the tires on the formatted output.

Rewrite Debug implementation for StackVec

---

src/config.rs
src/pagecache/iobuf.rs

I chased down the source of the rare deadlock I was seeing and made a few changes to fix it. There was insufficient synchronization between `make_stable()` and `maybe_seal_and_write_iobuf()`, so it was possible for make_stable to read the global error, see none, and wait forever, while the writing thread had notified waiters too early and then stored the error. Alternately, make_stable could read the global error, be preempted before it locked the intervals mutex, and miss the error and notify_all from the writing thread regardless of what order they were done in.
I was able to reproduce the issue more easily by running a quickcheck test with the "buffer write" failpoint in a loop, and then running that binary two to four times in parallel to increase contention. Depending on timing, I …

Fix rare deadlock from failpoint test in make_stable()

---

src/fail.rs
tests/test_tree_failpoints.rs

This implements #1048, associating a randomly generated u64 with each failpoint, and checking a different bit each time the failpoint is passed when deciding whether to return an error. I also included special handling for shrinking test cases, by progressively clearing bits in the bitset.
I threw several core-hours at this overnight (using `QUICKCHECK_TESTS=1000000 QUICKCHECK_MAX_TESTS=1000000`) and I got no crashes, and one deadlock with "log flusher failed to make_stable after 30 seconds." I have my suspicions that the deadlock has been a latent problem, predating this PR.

Trigger failpoints randomly on calls after set

---

.github/workflows/test.yml
src/histogram.rs

I noticed the histogram tests have bitrotted. This fixes one test to reflect the change in return type, and adds `--no-default-features` to a command line so that the histogram tests can run in the CI.

Fix histogram test

---

src/pagecache/reservation.rs

When running tests with configuration that disables the threadpool, I was getting a deadlock on the intervals mutex from anything that used transactions. The transaction commit eventually calls `Reservation::mark_writebatch()`, which locks the intervals mutex, calls `StabilityIntervals::mark_batch()`, and calls `Reservation::complete()`. The issue is that `Reservation::complete()` eventually spawns a threadpool task that calls `IoBufs::write_to_log()`, which also needs to lock the intervals mutex. If the threadpool is disabled, this closure will be called right away, and `write_to_log` will deadlock on the mutex.
This PR resolves the issue by dropping the intervals mutex guard before calling `Reservation::complete()`. This is a fairly naive fix, and I'm not familiar with recent related …

Drop mutex earlier to fix no-threads configuration

---

src/context.rs
src/db.rs
src/flusher.rs

@Erk- this may have an effect on some of the size issues you were seeing on FreeBSD, since I believe we may not have actually been spinning up the thread (still). Damn I hate conditional compilation.

refactor shutdown logic. clear some deprecated items. properly spin-up the flusher thread on the BSDs

---

src/arc.rs

Follow-up to #1096 to fix UB caught with Miri.
The allocation in copy_from_slice needs to be padded out to its
alignment, or else the slice methods called on it may cause undefined
behavior, since the slice's memory layout expects that memory to be
valid.
I also made Arc::copy_from_slice unsafe to call and private, to mirror
the corresponding function in the standard library.

copy_from_slice: unsafe, private; pad allocation

---

scripts/cross_compile.sh
src/debug_delay.rs
src/lib.rs
src/pagecache/iobuf.rs
src/pagecache/iterator.rs
src/pagecache/segment.rs
src/pagecache/snapshot.rs
tests/test_crash_recovery.rs

@divergentdave this might be cool for you - I was having some trouble reproducing the crash bug that sometimes happens on ci, #1085, so I added this simple probabilistic process crash that gets called sometimes from debug_delay, which is already threaded through all of our correctness-critical operations. Immediately the system exploded with panics :)
Now that this reproduction test is in, further work on this branch will aim to fix the bugs that are found with this fun new test.

Flush out more crash bugs with configurable process exit chance from debug_delay

---

Cargo.toml
scripts/cross_compile.sh
src/atomic_shim.rs
src/lib.rs
src/lru.rs
src/tree.rs

Rust's `std::sync` namespace does not provide `AtomicU64` and
`AtomicI64` for MIPS and PowerPC architectures.
This make the project not capable of being embedded into routers as
mentioned on #1070
This commit changes the references of `AtomicU64` and `AtomicI64` to use
a portable version, wich fallbacks to `crossbeam` Mutex when Atomics are
not available.
To compile against MIPS, the `block` initialization had to change, as
the Mutex is not `Copy`, and Rust's initialization of arrays only
supports `Copy` types. The `array-init` crate supports non-Copy types,
and that is why it was introduced.
It also introduces a `--features mutex` crate, which allows to compile
to x64 or any other architecture using the Mutex implementation, useful
for testing without cross-compiling.
Tests passes with: …

Port AtomicU64 to compile for MIPS

---

Cargo.toml
scripts/cross_compile.sh
src/config.rs
src/context.rs
src/db.rs
src/debug_delay.rs
src/fastcmp.rs
src/histogram.rs
src/lib.rs
src/lru.rs
src/pagecache/mod.rs
src/serialization.rs
src/stack.rs
src/sys_limits.rs
tests/test_crash_recovery.rs
tests/test_log.rs
tests/test_quiescent.rs
tests/test_space_leaks.rs
tests/test_tree.rs
tests/test_tree_failpoints.rs
tests/tree/mod.rs

This PR will add enough conditional compilation to support running tests with miri. So far, I have disabled use of the process's PID, turned off the body of try_lock(), and ignored the quickcheck tests, since they would take far too long to run. Miri is slow as tar, so using it would only be useful for spot-checking for unsoundness, not a CI job or anything.
Miri requires additional shims for mkdir and rmdir before this will work, I have changes in progress for that as well.
The first issue I've discovered thus far is that `crossbeam-epoch` has an unsound use of `std::mem::uninitialized`, creating a `std::Mem::ManuallyDrop<T>`. There is a PR at crossbeam-rs/crossbeam#458 that will fix this soon.
Relevant commands:
* Run a test: `cargo +nightly miri test --features=testing -- …

Miri support

---

src/arc.rs
src/ivec.rs

This PR rewrites the (unsafe code!) `From<Box<T>> for Arc<T>` implementation to allow dynamically sized types, like `std::sync::Arc` does. Constructing a fat pointer to a dynamically sized `ArcInner<T>` from a `*mut u8` thin pointer and the source fat pointer requires some extra gymnastics, see the comments for details. This implementation is then used to add back the `From<Box<[u8]>> for IVec` implementation. Also included: rewrite of Arc's Debug implementation to allow dynamically sized types, and a small test for the conversion. The unsafe code is modeled after the standard library's code, so it ought to be okay, plus I'm going to run tests with Miri overnight.
Fixes #1107

Conversion of boxed slices to Arc and IVec

---

src/db.rs

Because the new bound `AsRef<[u8]>` covers the previous type `&[u8]`, I think this is not a breaking change.

Make Db::drop_tree parameters match open_tree parameters.

---

CHANGELOG.md
Cargo.toml
src/result.rs

this causes compile times to be a few seconds faster

Make the backtrace crate optional for faster compile times

---

src/metrics.rs

Change-Id: If2c4c2d8485ef30e6e68eb107f9c23ebb40352a4
I have encountered subtract overflow panic during development. I have a made a fix identical to `log_reservations` approach using `cmp::max`.
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/ow/dev/rust/sled/src/metrics.rs:331:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
full backtrace
```
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1: backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:78
3: …
```

metrics: fix log_reservation_attempts subtract overflow

---

src/arc.rs
src/config.rs

Building with a recent nightly compiler yields a couple messages of `warning: attribute should be applied to a function`, and `warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!`. In these two places, `#[cold]` was applied to a statement or a block, whereas the attribute is only effective when applied to a function.
I don't think there is yet a good way to provide the intended hints to the compiler on stable, though if core_intrinsics is stabilized, the likely/unlikely intrinsics would work. Moreover, the #[cold] in src/arc.rs was on a call to std::process::abort(), and I'm hopeful that LLVM is able to infer that this branch is cold, because it ends with a call to a never-returning function.

Remove no-op #[cold] attributes

---

src/ivec.rs

This produces the same LLVM IR (modulo an SSA var name change) and assembly (literally identical).
<details><summary>The actual assembly, for curiosity's sake</summary>
```asm
inline:
push	r15
push	r14
push	rbx
sub	rsp, 32
cmp	rdx, 22
ja	.LBB7_2
mov	rbx, rdx
mov	r15, rsi
mov	r14, rdi
mov	edx, 22
sub	rdx, rbx
lea	rdi, [rsp + rbx]
add	rdi, 10
xor	esi, esi
call	qword ptr [rip + memset@GOTPCREL]
lea	rdi, [rsp + 10]
mov	rsi, r15
mov	rdx, rbx
call	qword ptr [rip + memcpy@GOTPCREL]
mov	byte ptr [r14], 0
mov	byte ptr [r14 + 1], bl
movups	xmm0, xmmword ptr [rsp + 10]
movups	xmmword ptr [r14 + 2], xmm0
mov	rax, qword ptr [rsp + 24]
mov	qword ptr [r14 + 16], rax
mov	rax, r14
add	rsp, 32
pop	rbx
pop	r14
pop	r15
ret
```
</details>

Replace unsafe IVec code with equivalent safe code

---

CHANGELOG.md
src/pagecache/segment.rs

Lone blobs were not being properly cleaned up upon replacement if they were replaced by another blob.

Fix blob space leak

---

CHANGELOG.md
src/atomic_shim.rs
src/batch.rs
src/config.rs
src/event_log.rs
src/fail.rs
src/flusher.rs
src/lib.rs
src/pagecache/blob_io.rs
src/pagecache/disk_pointer.rs
src/pagecache/iobuf.rs
src/pagecache/iterator.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/pagecache/reservation.rs
src/pagecache/segment.rs
src/pagecache/snapshot.rs
src/result.rs
src/serialization.rs
src/subscriber.rs
src/threadpool.rs
src/transaction.rs
tests/test_crash_recovery.rs

This facilitates the migration of metadata for tracking blob locations from the log + GC into the snapshot once the snapshot is known to contain the blob's lookup metadata. This is a step toward a more fully-fledged 2-component storage architecture where hot data remains in the log, but eventually is aged out into a lower-fragmentation place better suited to cold storage. The next step is to enable the fuzzy snapshotting code that already exists, which, combined with this work, will facilitate live migration of cold items out of the log.

push blobs to snapshot

---

src/pagecache/heap.rs

`libc::fallocate` does not have a shim implemented in Miri, this small patch conditionally disables hole punching in Miri to avoid calling it.

Don't try to call fallocate in Miri

---

tests/test_crash_recovery.rs

This PR improves the ergonomics of the test_crash_recovery test. Since this integration test has `harness = false` set, it is up to us to handle test filtering, console output, etc. These changes add console output that approximates what we see from the standard library test harness, and allow filtering out tests using the same command line argument interface. Sample output:
```
david@desktop:~/Code/sled$ cargo test --features=testing -- crash_tx
Finished test [unoptimized + debuginfo] target(s) in 0.05s
Running target/debug/deps/sled-e06fd382104117c8
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 29 filtered out
Running target/debug/deps/test_crash_recovery-83cd0a124e744f4b
running 1 test
test crash_tx ... ok
test result: ok. 1 passed; 3 filtered out
Running …
```

Add filtering and stderr output to no-harness test

---

benchmarks/stress2/Cargo.toml
benchmarks/stress2/src/main.rs
src/atomic_shim.rs
src/db.rs
src/fastlock.rs
src/lazy.rs
src/lib.rs
src/lru.rs
src/node.rs
src/pagecache/heap.rs
src/pagecache/iobuf.rs
src/pagecache/iterator.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/serialization.rs
src/threadpool.rs
src/tree.rs
src/varint.rs
tests/test_tree.rs

this large update changes how tree nodes are represented:
* a single contiguous allocation for a node's metadata, keys, and values
* variable offset and length bytes
* avoids offset tables when keys and values are fixed length
* combines offset tables when keys and values are both variable length
* zero additional serialization / deserialization effort
* likely addresses cache sizing problems
over time, this makes it easy to take advantage of
* eytzinger layouts #1219 
* cheaper cache accounting
* far more compact in-memory representations
* essentially free serialization

single-allocation nodes

---

src/db.rs
src/pagecache/mod.rs
src/pagecache/pagetable.rs

Make get_meta and get_idgen infallible. Make PageTable::get always return a PageView, as allocate enforces that pages are present at all times with an allocation mutex

pagecache simplifications

---

CHANGELOG.md
src/db.rs
src/ivec.rs
src/lib.rs
src/meta.rs
src/node.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/serialization.rs
src/tree.rs
tests/test_tree.rs

This reduces the update pressure for contiguous nodes by buffering updates in an in-memory "overlay" that sits on top of an Arc-wrapped contiguous Node, and only when the node is rewritten due to GC or reaching the max frag threshold will it be consolidated in one go. 
This essentially maps the overlay to Link updates, and the backing NodeInner to fully rewritten nodes.

Use an in-memory overlay for receiving node updates before merging them into the backing NodeInner in a batch

---

src/pagecache/mod.rs

Most memory blow-up issues stem from something holding on to a crossbeam-epoch guard for too long. This addresses one of the offenders.

avoid long pins on snapshot generation

---

src/node.rs
src/pagecache/iobuf.rs

by reducing contention, we also significantly reduce memory usage as this causes far less build-up in the threadpool and in the EBR collector

contention reductions

---

src/node.rs
src/pagecache/mod.rs

* node can now store up to 2^32 children
* values of fixed length 0 are now properly omitted, allowing both keys and values to potentially collapse to a single header, lo key and hi key storing all information for a node

node enhancements

---

src/context.rs
src/db.rs
src/lib.rs
src/pagecache/mod.rs
src/threadpool.rs

Hey there! Congrats on the awesome crate 🎉 .
While coding something on iOS we noticed the changes were not being synced.
From some commit messages I found that the rationale behind the cfg gate was to only enable the flusher in platforms with support for threads. This enables the flusher for iOS.
I can add some docs if that's a goal, just not sure where given that `Config`'s `flush_every_ms` options is `#[doc(hidden)]`.

feat: Enable the flusher for iOS

---

src/db.rs
tests/test_tree.rs

Hello guys, this is my 1st contribution to the sled embedded database. This PR is to add a method to the db struct to be able to see if there is already a tree with that name in the database.

Add contains_tree method to the Db, related to issue 1297

---

src/oneshot.rs
src/subscriber.rs

Fixes https://github.com/spacejam/sled/issues/1313
Add a field on Subscriber to store a oneshot after getting a pending poll. It's possible we'll need to pull some extra waker shenanigans in order to ensure we wake up when the oneshot becomes ready, but I'm not versed enough in this codebase to know that yet.
This change also removes an unneeded use of `unsafe` (I think this is fine, but let me know if it was there for a reason)

Store pending oneshot for subscriber future

---

src/db.rs
src/fastlock.rs
src/pagecache/disk_pointer.rs
src/subscriber.rs
src/tree.rs
tests/test_tree.rs

This PR is made to address the issue https://github.com/spacejam/sled/issues/1177. It gives a 2nd method to watch_prefix to get a subscriber given a prefix. But the method gives the choice to decide how large the subscriber channel is. I have also used the line, cargo fmt this means it also includes a reformatted code.

Add a method that gives a subscriber where the channel size can be chosen

---

src/threadpool.rs

While performing work in a threadpool, always perform spawned work inline instead of chucking it into a queue, which could cause cyclical write stabilization dependencies. This should avoid some deadlock risk that I've been thinking may be possible.

never spawn work from the threadpool back into the threadpool queue

---

src/histogram.rs
src/metrics.rs
src/pagecache/iterator.rs
src/pagecache/mod.rs
src/pagecache/snapshot.rs
src/serialization.rs

By using cargo clippy on normal mode and with the testing feature on, I got rid of some cargo warnings that I got out of my own build and that of the pipeline.
The only warning I could not get through was on src/result.rs file on 84. So the fix was instead of cloning the bt variable, I just dereferenced it. But this made compiling with testing feature not work.

apply cargo clippy fix

---

src/ivec.rs

This will move the minimum supported rust version to 1.51, which may or may not be acceptable.

Use const generics for IVec::from array

---

src/subscriber.rs
src/tree.rs

After 1024 insertions of the same key-value pair, the SyncSender blocks.
This fixes issue #1380

Fix: insert deadlock #1380

---

CHANGELOG.md
README.md
scripts/cross_compile.sh
src/context.rs
src/db.rs
src/lib.rs
src/pagecache/iobuf.rs
src/pagecache/logger.rs
src/pagecache/mod.rs
src/threadpool.rs

This change has been a long time coming, as needing to punt all maintenance work to any caller thread over time has really caused a lot of code complexity around logging and garbage collection to build-up. This change reasserts what sled began as, which is an embedded database with its first aim being to support higher scale distributed stateful systems, which will stand to benefit dramatically from being able to rely on thread support for specific logging and GC functionality over time. This change primarily unlocks some logging changes that I'd like to implement soon that should really simplify the writepath.

Require threads on all platforms.

---

src/node.rs

The build was failing when `size_of::<usize> < 8` with the error "this arithmetic operation will overflow".
This error is not emitted when running "cargo check" and hence not caught by the CI.

Fixes 32 bits systems compatibility

---

src/db.rs
src/heap.rs
src/metadata_store.rs
tests/test_tree.rs

Fixes a few clippy lints and makes it so that `as_ref` is only called once on keys (out of concern for impure `AsRef` implementations).

bloodstone: A few nits

---

.github/workflows/test.yml
Cargo.toml
scripts/cgtest.sh
src/concurrency_control.rs
src/config.rs
src/ebr/internal.rs
src/ebr/mod.rs
src/lib.rs
src/node.rs
src/pagecache/heap.rs

Rather than having a feature named "testing" that external users might
be tempted to incorrectly use (and a detailed comment discouraging them,
which people may or may not see), rename the feature to
"for-internal-testing-only" so that nobody gets any wrong ideas about
whether it's meant for them.

Rename "testing" feature to "for-internal-testing-only"

---

Cargo.toml
src/db.rs
src/flush_epoch.rs
src/heap.rs
src/lib.rs
src/metadata_store.rs
tests/test_tree.rs

This starts freeing empty tree nodes to allow their memory to be reclaimed and fixes a number of race conditions related to the previous way that dirty pages were being tracked. A separate PR will add reclamation for the heap-based on-disk storage system.

sled 1.0 alpha merges and storage refactor

---

.gitignore
src/block_checker.rs
src/db.rs
src/lib.rs
src/object_cache.rs
src/tree.rs
tests/test_crash_recovery.rs
tests/test_tree.rs
tests/test_tree_failpoints.rs

[bloodstone] merge empty leaf with right sibling, consuming right sibling

---

src/leaf.rs
src/lib.rs
src/object_cache.rs
src/tree.rs
tests/00_regression.rs
tests/test_tree_failpoints.rs
tests/tree/mod.rs

InlineArray will inline anything up to 7 bytes on the stack. that often doesn't kick in for many types of keys in the database, but with prefix encoding it should kick in far more often. Suffix truncation is already implemented for reducing key sizes in the node index.

[bloodstone] implement prefix encoding
