- Cargo.toml
- src/config.rs
- src/lib.rs
- src/log/iobuf.rs
- src/log/lss.rs
- src/log/mod.rs
- src/page.rs
- src/radix.rs
- src/tree/mod.rs
- tests/test_tree.rs
I wanted to get the docs into a better spot, so I just filled them in.
> Add docs to all exported things.

- .travis.yml
- Cargo.toml
- README.md
- src/bound.rs
- src/lib.rs
- src/log/iobuf.rs
- src/log/lss.rs
- src/log/periodic_flusher.rs
- src/log/reservation.rs
- src/page/hash.rs
- src/page/lru.rs
- src/page/mod.rs
- src/page/page_cache.rs
- src/radix.rs
- src/stack.rs
- src/tree/data.rs
- src/tree/mod.rs
- src/tree/node.rs
- tests/test_pagecache.rs
I've added the clippy tool, which will now cause build errors when it's not happy. Clippy will run with `cargo test` but not `cargo build`.
> add clippy

- src/config.rs
- tests/test_pagecache.rs
- tests/test_tree.rs
this makes running tests locally much faster
> speed up tests

- Cargo.toml
- src/bin/bench.rs
Closes #55 
Can be tested via `cargo build && ./target/debug/bench --num-threads 42`
> Read CLI args for benchmarking tool

- src/stack.rs
we use unprotected here because we have a `Drop` order issue, where a thread panics if it tries to send the pagecache a freed logical PageID after the coco epoch system is destroyed. It's not necessary to guarantee that any loaded pointers remain valid during the course of this function's execution, so using unprotected here is OK I think, and fixes the panic.
> fix bug where the garbage system was dropped before calling epoch::pin

- CONTRIBUTING.md
- Cargo.toml
- src/page/page_cache.rs
* fix bug in short-circuit read logic
* fix bug in page_in logic for storing retrieved fragments
> two bugfixes in page_in

- Cargo.toml
- src/ds/radix.rs
- src/ds/stack.rs
- src/page/mod.rs
- src/page/page_cache.rs
> make Radix and Stack require 'static on the contained type. closes #107.

- .gitignore
- Cargo.toml
- README.md
- hack/flamegraph.sh
- src/bin/bench.rs
- src/bin/stress.rs
- src/bin/stress2.rs
- src/c.rs
- src/config.rs
- src/lib.rs
- src/log/lss.rs
- src/metrics.rs
- src/page/page_cache.rs
- src/tree/mod.rs
- tests/test_log.rs
- tests/test_pagecache.rs
- tests/test_tree.rs
probably better to avoid associations with the racial slur database on google :)
this name feels fast and fun (and scary to responsible adults) to me!
> rename rsdb to sled

- hack/execution_explorer.py
this is a fun little tool for running compiled programs (that have symbols built-in) in a deterministic way for finding bugs in concurrent algorithms, and replaying them deterministically
> check-in execution explorer

- Cargo.toml
- src/bin/bench.rs
> Add bench statistics

- native/src/lib.rs
- src/config.rs
- src/tree/tree.rs
> Read-only mode

- src/bin/cyclical_linearizability.rs
- src/config.rs
- src/io/iterator.rs
- src/io/log.rs
- src/io/segment.rs
possibly closes some of the cyclical linearizability bugs, need to keep burning in
> fix segment accountant recovery. closes #183.

- src/config.rs
- src/io/snapshot.rs
@daboross internally I went with OsString instead of PathBuf because we append suffixes to paths far more often than dealing with subdirectories
> use AsRef<Path> for paths. closes #178

- crates/pagecache/Cargo.toml
- crates/pagecache/src/io/iobuf.rs
- crates/pagecache/src/io/log.rs
- crates/pagecache/src/lib.rs
Closes #224.  The motivation behind this PR is explained in that issue :)
> Rip out cpuprofiler and env_logger

- crates/pagecache/src/result.rs
> implement Display for Error

- crates/pagecache/src/io/iobuf.rs
- crates/pagecache/src/io/log.rs
- crates/pagecache/src/io/segment.rs
This change was discussed in #230.  Closes #230.
@spacejam Thanks for guiding me on this issue!
> Remove prev from SegmentHeader

- crates/pagecache/src/config.rs
- crates/pagecache/src/io/snapshot.rs
- tests/tests/test_crash_recovery.rs
- tests/tests/test_tree.rs
> put created files into a subdirectory

- crates/pagecache/src/io/page_cache.rs
This removes several unwrapping points, handling options via match
statements instead. It also bubbles up a few additional error cases.
> pagecache: get rid of several unwraps

- crates/pagecache/src/result.rs
From trait is too strict in this case
> change trait bound in error cast to Into

- crates/model/src/lib.rs
* Fix some doctests on the way.
* Let the default (config-less) mode follow the PROPTEST_CASES
environment variable if specified.
> model: Add ability to pass config to linearizable!

- crates/pagecache/Cargo.toml
- crates/pagecache/src/hash/crc16.rs
- crates/pagecache/src/iobuf.rs
- crates/pagecache/src/metrics.rs
- crates/pagecache/src/util.rs
- crates/sled/Cargo.toml
> add no_inline feature to pagecache

- crates/sled/src/data.rs
- crates/sled/src/materializer.rs
- crates/sled/src/node.rs
- crates/sled/src/prefix.rs
- crates/sled/src/tree.rs
- crates/sled_sync/src/lib.rs
> fix some clippy warnings

- README.md
> Add Discord badge to README.md

- crates/pagecache/src/config.rs
> Allow path to be overridden for temporary databases. Closes #431.

- crates/sled/src/tree.rs
> Use Cow to reduce the cost of page cloning during recursive splits

- crates/pagetable/src/lib.rs
> Remove redundant load operation on the 2mb page

- .travis.yml
- crates/deterministic/src/context.rs
- crates/deterministic/src/file.rs
- crates/deterministic/src/lib.rs
- crates/model/src/lib.rs
- crates/pagecache/src/config.rs
- crates/pagecache/src/ds/lru.rs
- crates/pagecache/src/ds/stack.rs
- crates/pagecache/src/flusher.rs
- crates/pagecache/src/iobuf.rs
- crates/pagecache/src/logger.rs
- crates/pagecache/src/materializer.rs
- crates/pagecache/src/pagecache.rs
- crates/pagecache/src/segment.rs
- crates/pagecache/src/snapshot.rs
- crates/pagetable/src/lib.rs
- crates/sled/src/subscription.rs
- crates/sled_sync/src/debug_delay.rs
- tests/src/lib.rs
- tests/src/tree.rs
- tests/tests/test_log.rs
- tests/tests/test_pagecache.rs
- tests/tests/test_tree_failpoints.rs
Fixed the windows build and the travis build for PRs, so this should be a bit easier in the future.
This PR has mostly isolated small changes so it should be quick to review. The cleanup commit has a list of broader categories I included here from other one.
> some clippy cleanup

- crates/sled/src/db.rs
It seems weird to me, I think it's probably related to a piece of old code.
I am probably wrong :)
> Clean the Db Deref implementation

- .travis.yml
- crates/pagecache/Cargo.toml
- crates/pagecache/src/blob_io.rs
- crates/pagecache/src/iobuf.rs
- crates/pagecache/src/lib.rs
- crates/pagecache/src/logger.rs
- crates/pagecache/src/pagecache.rs
- crates/pagecache/src/reader.rs
- crates/pagecache/src/reservation.rs
- crates/pagecache/src/segment.rs
- crates/pagecache/src/snapshot.rs
- crates/sled/Cargo.toml
- crates/sled/src/db.rs
- crates/sled/src/meta.rs
- tests/Cargo.toml
- tests/tests/test_tree.rs
this will significantly reduce contention on the segment accountant mutex
> skip mark link on previously linked

- crates/sled/src/node.rs
The `get_internal` operation moved from 25% to 15% and make my program take from 28mins to 25mins.
[flamegraphs-before-after-patch.zip](https://github.com/spacejam/sled/files/2999208/before-after-patch.zip)
> Prefer inserting at index instead of sorting

- crates/sled/src/tree.rs
I would like to know what your thoughts about the fact that my method returns and unnamed `Iterator` type. Do you think it could be better to create a concrete Iterator type?
Note that [the only traits that a `TakeWhile` transfert](https://doc.rust-lang.org/std/iter/struct.TakeWhile.html) is the `Iterator` and the `FusedIterator` ones, it is not possible to have a `DoubleEndedIterator` using `TakeWhile` therefor we do only loose the `Debug`, `FusedIterator` and `Clone` traits impls by exposing an unnamed type this way.
> Introduce the Tree scan_prefix method

- benchmarks/stress2/src/main.rs
- crates/pagecache/src/config.rs
- crates/pagecache/src/ds/pagetable.rs
- crates/pagecache/src/iobuf.rs
- crates/pagecache/src/iterator.rs
- crates/pagecache/src/logger.rs
- crates/pagecache/src/pagecache.rs
- crates/pagecache/src/segment.rs
- crates/pagecache/src/snapshot.rs
- tests/tests/test_log.rs
- tests/tests/test_tree_failpoints.rs
these commits seek to reduce overall complexity and reduce some latency during system initialization that corresponds to poor test and benchmarking performance when hundreds or thousands of instances need to be created quickly
> test optimizations

- crates/pagecache/src/config.rs
- crates/pagecache/src/ds/pagetable.rs
- crates/pagecache/src/pagecache.rs
- crates/pagecache/src/snapshot.rs
> optimize startup

- README.md
- benchmarks/stress2/src/main.rs
- crates/sled/src/batch.rs
- crates/sled/src/lib.rs
- crates/sled/src/tree.rs
- examples/playground/src/main.rs
- tests/src/tree.rs
- tests/tests/test_tree.rs
- tests/tests/test_tree_failpoints.rs
> Deprecate Tree::del and replace it by Tree::remove

- README.md
- benchmarks/stress2/src/main.rs
- crates/sled/src/batch.rs
- crates/sled/src/db.rs
- crates/sled/src/lib.rs
- crates/sled/src/tree.rs
- examples/playground/src/main.rs
- tests/src/tree.rs
- tests/tests/test_crash_recovery.rs
- tests/tests/test_tree.rs
- tests/tests/test_tree_failpoints.rs
> Deprecate Tree::set and replace it by Tree::insert

- crates/pagecache/README.md
- crates/pagecache/src/config.rs
- crates/pagecache/src/lib.rs
- crates/pagecache/src/materializer.rs
- crates/pagecache/src/pagecache.rs
- crates/sled/src/db.rs
- crates/sled/src/frag.rs
- crates/sled/src/lib.rs
- crates/sled/src/materializer.rs
- crates/sled/src/meta.rs
- crates/sled/src/node.rs
- crates/sled/src/tree.rs
- tests/src/tree.rs
- tests/tests/test_pagecache.rs
this dramatically simplifies internal architectural concerns going forward
> Reimplement merge operator functionality on top of a CAS 

- crates/pagecache/src/blob_io.rs
- crates/pagecache/src/config.rs
- crates/pagecache/src/constants.rs
- crates/pagecache/src/diskptr.rs
- crates/pagecache/src/ds/dll.rs
- crates/pagecache/src/ds/lru.rs
- crates/pagecache/src/ds/pagetable.rs
- crates/pagecache/src/ds/stack.rs
- crates/pagecache/src/iobuf.rs
- crates/pagecache/src/iterator.rs
- crates/pagecache/src/lazy.rs
- crates/pagecache/src/logger.rs
- crates/pagecache/src/pagecache.rs
- crates/pagecache/src/promise.rs
- crates/pagecache/src/reader.rs
- crates/pagecache/src/result.rs
- crates/pagecache/src/segment.rs
- crates/pagecache/src/snapshot.rs
A little bit of the work needed for #760.
> Fix some of the clippy advices

- azure-pipelines.yml
and reuse bash for loops to optimize code boilerplate
> fix cross-compile script to print a platform which broke the build

- CHANGELOG.md
- crates/sled/src/subscription.rs
- crates/sled/src/tree.rs
> Rename Event variants

- crates/sled/src/tx.rs
> Implement std::error::Error for TransactionError

- tests/tests/test_crash_recovery.rs
This implements #779. I added the new tests inside `test_crash_recovery.rs`, and shared some utility functions. This test opens a `Db` with one `Tree`, and repeatedly applies `Batch`es that update the same eight keys. 90% of the time, it sets all of them to one more than their previous time, and 10% of the time, it deletes all the keys. The database is verified upon opening each time, to confirm that it's either empty, or it has all eight keys, and their values are equal. Similar to the other crash recovery tests, the child process will be killed at a random delay from either before the database is opened, or after.
Running this test locally, I uncovered the following failures:
```
The application panicked (crashed).
Message:  assertion failed: `(left == right)`
left: `Some(11000)`, …
```
> Add crash recovery test for atomic batches. Closes #779

- CHANGELOG.md
- benchmarks/stress2/src/main.rs
- examples/crdt_merge_store.rs
- examples/playground.rs
- src/config.rs
- src/context.rs
- src/db.rs
- src/event_log.rs
- src/lib.rs
- src/pagecache/iobuf.rs
- src/pagecache/iterator.rs
- src/pagecache/logger.rs
- src/pagecache/pagecache.rs
- src/pagecache/segment.rs
- src/pagecache/snapshot.rs
- src/tree.rs
- tests/test_crash_recovery.rs
- tests/test_log.rs
- tests/test_pagecache.rs
- tests/test_tree.rs
- tests/test_tree_failpoints.rs
- tests/tree/mod.rs
* Remove ConfigBuilder
* Add Config::open
* Persist config settings using a simple text format that does not rely on serde
* Clean up test_log.rs
> Big configuration rework

- src/pagecache/io_uring.rs
- src/pagecache/iobuf.rs
fyi @sitano just doing some small clean-ups based on the output from clippy here
> clippy cleanup

- src/pagecache/blob_io.rs
- tests/test_tree_failpoints.rs
added fail points for all io operations (except in gc_blobs)
test_tree_failpoints test did not trigger any fail points in gc_blobs
so I removed them
issue: https://github.com/spacejam/sled/issues/530
> WIP failpoints in blob_io.rs

- src/lib.rs
- src/pagecache/io_uring.rs
continuing https://github.com/spacejam/sled/pull/877.
- use IOSQE_FIXED_FILE for writing registered fd
- fix converting io_uring errors to os codes
> WIP: io_uring: minor updates

- src/pagecache/segment.rs
This fixes one typo and adds a little stylistic consistency in this file
> Miscellaneous cleanups in src/pagecache/segment.rs

- src/pagecache/io_uring.rs
- src/pagecache/iobuf.rs
This PR fixes the work of basic io_uring support in iobuf.
The original idea of delayed async fsync did not work.
It introduced a race condition on parallel writes even
for very small queues (4), that, it seems like, managed to
reorder. With randomized crashes recovery failed to gracefully
manage this kind of situations. So I am rolling back this idea
for now until the future generation of logging and recovery.
One strange behavior I still observe is long-running
`quickcheck_tree_matches_btreemap`, but it least it passes
all the tests.
I know all io_uring stuff will be soon replaced with `rio`
but at least this previous generation thing now works and
can be there for the sake of history.
Moreover, this current implementation performs even worse
than plain pwrite_all+fsync_range:
```
write …
```
> iobuf/io_uring: async fsync is not an option

- src/concurrency_control.rs
This is the completion of #965 
The race condition is when two writers come in, only the first would block on the upgrade to flush through. This causes all of the first writers to wait on the upgrade's completion.
> Fix race condition in the CC upgrade path

- CHANGELOG.md
- src/config.rs
- src/lib.rs
- src/pagecache/pagetable.rs
- src/pagecache/snapshot.rs
- src/threadpool.rs
> Reduce default segment size to 512kb. Simplify configuration

- src/pagecache/iobuf.rs
- src/pagecache/mod.rs
- src/pagecache/reservation.rs
- src/pagecache/segment.rs
- src/transaction.rs
- src/tree.rs
- tests/test_crash_recovery.rs
- tests/test_log.rs
> Track max segment pegs in the SegmentAccountant. 

- src/pagecache/iobuf.rs
- src/pagecache/reservation.rs
- src/pagecache/segment.rs
- tests/test_log.rs
> Mark all batch segments as blocked on the end of the batch in mark_peg

- bindings/sled-native/Cargo.toml
- bindings/sled-native/README.md
- bindings/sled-native/cbindgen.toml
I added a small readme and the cbindgen configuration that seems working fine.
> Initial cargo-c support

- src/pagecache/pagetable.rs
(cherry picked from commit fbc78ceb9a47f177945ad147f5237aefabdf0af6)
> Adjust PageTable max sizes to cut memory usage by a bit

- src/result.rs
- src/tree.rs
> std error for cas errors

- CHANGELOG.md
- benchmarks/stress2/Cargo.toml
- benchmarks/stress2/src/main.rs
- scripts/sanitizers.sh
- src/dll.rs
- src/lru.rs
- src/node.rs
- src/pagecache/constants.rs
- src/pagecache/pagetable.rs
- src/pagecache/segment.rs
- src/stack.rs
> power of 2 cache sizes, segmented lock-free queue for lower memory flat combining on cache accesses

- src/lib.rs
- src/tree.rs
> implement stateful merge operators

- src/pagecache/blob_io.rs
> Continue with blob gc if an unexpected file is discovered

- CHANGELOG.md
- bindings/sled-native/src/lib.rs
- src/config.rs
- src/db.rs
- src/pagecache/mod.rs
- src/tree.rs
this has not had enough attention, and it is low priority for now. Instead of fighting bugs that will keep popping up around this due to the architecture changing, I'm going to remove it completely and at a later time properly implement it. it seems to have bugs pop up for everyone who tries it.
> Remove buggy read-only mode

- src/pagecache/mod.rs
- src/pagecache/snapshot.rs
Convert the PageTable into a vector of PageState.
> [978] Fuzzy checkpointing

- src/transaction.rs
Looks like some remnant code, please check...
> Removed unused code in TransactionalTree:stage()

- src/concurrency_control.rs
brings 16 threads doing small random point reads on an intel 9900k from 13.9m reads/s to 15.4m/s
> Reduce the number of atomic operations required to perform dynamic concurrency control

- src/subscriber.rs
This should fix the deadlock from spacejam/sled#1152
https://github.com/spacejam/sled/issues/1152#issuecomment-686390978
> fix destructor deadlock from issue #1152

- src/batch.rs
- src/transaction.rs
- src/tree.rs
This closes #999
All the changes were mechanical, so I wouldn't expect there to be any issue.
> Widen trait bounds to allow Into

- Cargo.toml
- src/pagecache/header.rs
- src/pagecache/iobuf.rs
- src/pagecache/logger.rs
- src/pagecache/mod.rs
- src/threadpool.rs
thanks to @poppindouble for diving deep into the guts of the system and asking questions that caused me to realize this could be simplified!
> inline maxed header, remove unnecessarily complex linearizer

- src/config.rs
- src/context.rs
- src/flusher.rs
- src/pagecache/mod.rs
- src/pagecache/snapshot.rs
> Enable fuzzy snapshotting

- src/pagecache/heap.rs
cc @divergentdave I've taken your conditional compilation and consolidated it with the existing conditional compilation at the top of punch_hole's body
> small refactor of miri no hole punching

- Cargo.toml
- src/pagecache/heap.rs
- tests/test_crash_recovery.rs
fyi @divergentdave this speeds up testing a little by running the crash tests in parallel
> multithread crash tests

- src/config.rs
- src/db.rs
- src/iter.rs
- src/lib.rs
- src/metrics.rs
- src/pagecache/iobuf.rs
- src/pagecache/iterator.rs
- src/pagecache/logger.rs
- src/pagecache/mod.rs
- src/pagecache/pagetable.rs
- src/pagecache/segment.rs
- src/pagecache/snapshot.rs
- src/tree.rs
From my measurements this decreases memory usage by more than 20 MB
> Disable everything related to metrics if the feature is disabled

- .github/workflows/test.yml
- src/config.rs
- src/db.rs
- src/fail.rs
- src/flusher.rs
- src/lib.rs
- src/meta.rs
- src/node.rs
- src/pagecache/iobuf.rs
- src/pagecache/iterator.rs
- src/pagecache/logger.rs
- src/pagecache/mod.rs
- src/pagecache/reservation.rs
- src/pagecache/segment.rs
- src/pagecache/snapshot.rs
- src/serialization.rs
- src/threadpool.rs
- src/tree.rs
- tests/test_log.rs
- tests/test_tree.rs
- tests/test_tree_failpoints.rs
this is a significant step towards pointer swizzling support, as well as addresses several correctness issues that have been discovered through increased fault injection (the `pwrite partial` failpoint in particular has caused a number of interesting bugs to pop out).
> reduced size tracking and error handling rework

- src/ebr/deferred.rs
- src/node.rs
- src/pagecache/logger.rs
- tests/test_crash_recovery.rs
- tests/test_log.rs
- tests/test_tree_failpoints.rs
- tests/tree/mod.rs
Passes tests
Would have added these to #1359 but these were found with cargo +nightly, so if you dislike the style, feel free to close
> Additional clippy's from nightly

- src/ebr/deferred.rs
If `size_of::<F>` < `size_of::<Data>`, the remaining bytes would be uninitialised - thus, calling `assume_init` would cause UB, as noted by Miri. Storing the data as `MaybeUninit` and casting to the correct `FnOnce()` object before reading it fixes this, only using initialized bytes.
> Prevent UB with `assume_init` on uninit bytes
